[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = [
    "setuptools>=45.0", "setuptools_scm>=6.0", "wheel",
]
build-backend = "setuptools.build_meta"
